# Site settings
title: blog.mgiuffrida.com
email:
description: > # this means to ignore newlines until "baseurl:"
  Programming and stuff.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.mgiuffrida.com" # the base hostname & protocol for your site
twitter_username: mgiuffrida
github_username:  mgiuffrida

# Conversion
markdown: kramdown
highlighter: rouge

# Outputting
timezone: UTC # Anything else doesn't treat offsets correctly.

# Forced by GitHub
safe: true
lsi: false
source: .

gems:
  - jemoji
