# Site settings
title: mgiuffrida.github.io
email:
description: > # this means to ignore newlines until "baseurl:"
  Programming and stuff. Definitely stuff.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://mgiuffrida.github.io" # the base hostname & protocol for your site
twitter_username: mgiuffrida
github_username:  mgiuffrida

# Conversion
markdown: rdiscount
rdiscount:
  extensions: ["smart"]
highlighter: pygments

# Outputting
timezone: UTC # Anything else doesn't treat offsets correctly.

# Forced by GitHub
safe: true
lsi: false
source: .

gems:
  - jemoji
